name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: the-guardian-cuu
      SKIP_NODE: false
      NODE_VERSION_OVERRIDE: 12
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
